### ISSUE TITLE
Leaderboard commands do not respond

### ISSUE THREAD

**Issue by cyanogus** [PyBotDevs/isobot#279]
When `/leaderboard_nw` or `/leaderboard_levels` are run, they do not respond.
It is either a problem with the bot hanging when fetching user api data, or that there are some issues reading the database.

**Comment by notsniped** [comment]
Seems most likely a problem with the bot hanging. I would either reduce the number of api requests in one command or remove it completely.

**Comment by notsniped** [comment]
I found a way to delay interaction responses

```py
await ctx.defer()
```

**Comment by notsniped** [comment]
So I'll keep the default amount of users (10 users) pulled from API, but use `await ctx.defer()` to prevent the interaction from expiring before it hits `respond()`  trigger.

**Comment by notsniped** [comment]
Okay, so I noticed that the library is currently broken. The method for fetching user data from the API is missing, and if I use an alias it returns an internal library error which I cannot fix. 

I will attempt to get it resolved by PyCord some day, but for now I am disabling the commands as I can't help it right now.
