### ISSUE TITLE
Add db management system libraries for rest of the databases

### ISSUE THREAD

**Issue by cyanogus** [PyBotDevs/isobot#293]
This was added for the currency system's database. Since no problems were reported from use after it's implementation, I feel like it's time to implement this change to the other databases as well.

**Comment by notsniped** [comment]
:+1:

**Comment by cyanogus** [comment]
#298

**Comment by notsniped** [comment]
Levelling database migrated to framework in #307

**Comment by notsniped** [comment]
The PR related to this issue has been closed, so I am also closing this issue. Thank you.
