### ISSUE TITLE
Add weapons to the shop

### ISSUE THREAD

**Issue by cyanogus** [PyBotDevs/isobot#294]
Referenced from #250

**Comment by notsniped** [comment]
I realise this idea is actually quite insensitive, because of _(ykw)_ in America. So, in that logic, I will not be proceeding with this idea.

**Comment by notsniped** [comment]
I realise this idea is actually quite insensitive, because of (ykw) in America. So, in that logic, I will not be proceeding with this idea.

**Comment by notsniped** [comment]
I realise this idea is actually quite insensitive, because of (ykw) in America. So, in that logic, I will not be proceeding with this idea.
