### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by notsniped** [PyBotDevs/isobot#52]
# Tasks
### ***All tasks need to be completed to push this rework as an isobot-stable update!*** 
- [x] #55 
- [x] #76 
- [x] #78
- [x] #93 
- [x] #91
- [x] #151
- [x] #87 (Solvable by #77)
- [x] #53 
- [x] #166
- [x] #61
- [x] #122
- [x] #170
- [x] #67 
- [x] #84
- [x] #152
- [x] #150 
- [x] #155

*These core feature updates are final, however more features will be added after this!*

## Delayed Changes (will be worked on after main-release date)
* Add server leaderboard and global leaderboard info command

**Comment by thatOneArchUser** [comment]
bro actually created an issue on his own repo :skull:

**Comment by notsniped** [comment]
> bro actually created an issue on his own repo skull

It's an issue for the repo's tasklist. Issue because it always shows up.

**Comment by notsniped** [comment]
One last core feature to add and then the new codebase will go live on isobot-stable!

**Comment by notsniped** [comment]
> Add server leaderboard and global leaderboard info command
This will be delayed past codebase merge date as we are currently fixing existing bugs with the bot.

**Comment by notsniped** [comment]
**Important Announcement!**
This list is now being closed as isobot-lazer has been merged with isobot. Thank you all for following along in isobot-lazer project!

**Comment by notsniped** [comment]
**Important Announcement!**
This list is now being closed as isobot-lazer has been merged with isobot. Thank you all for following along in isobot-lazer project!
